version: 1.0.{build}
branches:
  # whitelist
  only:
    - master
    - develop

deploy: off

init:
  - echo "Filesystem root:"
  - ps: "ls -Name \"C:/\""
  - echo "Installed SDKs:"
  - ps: "ls -Name \"C:/Program Files/Microsoft SDKs/Windows\""
  - echo "Set python path"
  - "SET PATH=\\Python34;\\Python34\\Scripts;%PATH%"


clone_depth: 5

environment:
  matrix:
  - PYTHON: "C:\\Python34"
    PYTHON_VERSION: "3.4.1"
    PYTHON_ARCH: "32"

install:
  - ps: Start-FileDownload "http://downloads.sourceforge.net/pyqt/PyQt5/PyQt-5.3.2/PyQt5-5.3.2-gpl-Py3.4-Qt5.3.1-x32.exe" -FileName $env:temp/pyqt5_install.exe
  - ps: "& $env:temp/pyqt5_install.exe /S"
  - ps: "Wait-Process -Name pyqt5_install -Timeout 600"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -c \"import PyQt5\""
  - "pip --version"
build:
  verbosity: minimal

build_script:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - "pip install -r requirements.txt"
  - "python setup.py build"
  - cd build/exe.win32-3.4
  - ps: "& 7z a -r ../pomito.$($env:APPVEYOR_BUILD_VERSION).win32.zip ."

test_script:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - "nosetests"

artifacts:
  - path: build/*.zip
